[package]
name = "zram-generator"
version = "0.1.2"
authors = ["Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>"]
license = "MIT"
description = "Systemd unit generator for zram swap devices"
homepage = "https://github.com/systemd/zram-generator"
edition = "2018"

[dependencies]
anyhow = "1"
clap = { version = "2.33", default-features = false }
rust-ini = "0.15"

[dev-dependencies]
tempfile = "3"

[profile.release]
lto = true
